services:
  postgres:
    image: postgres:15
    container_name: db_postgres
    env_file: .env
    environment:
      - TZ=America/Sao_Paulo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./news_aggregator/database/migrations:/docker-entrypoint-initdb.d

  api_front:
    build: 
      context: .
      dockerfile: ./news_aggregator/api_front/Dockerfile
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5010:5010"
    volumes:
      - ./news_aggregator:/app/news_aggregator

  newsapi_collector:
    build:
      context: .
      dockerfile: ./news_aggregator/collectors/newsapi_collector/Dockerfile
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      postgres:
        condition: service_healthy     
    volumes:
      - ./news_aggregator:/app/news_aggregator


  worldnews_collector:
    build: 
      context: .
      dockerfile: ./news_aggregator/collectors/worldnews_collector/Dockerfile
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      postgres:
        condition: service_healthy     
    volumes:
      - ./news_aggregator:/app/news_aggregator


volumes:
  pgdata:
